### ISSUE TITLE
Viewing all my uploads shows benches I haven't tagged... 

### ISSUE THREAD

**Issue by MikeHingley22** [openbenches/openbenches.org#294] opened 2023-03-18 13:38 UTC
I thought I'd see what benches I uploaded, but the map shows...

https://openbenches.org/user/6074/

![Uploading Screenshot_20230318_133659_DuckDuckGo.jpg…]()

**Comment by MikeHingley22** [comment] 2023-03-18 13:41
I'm at Sandwell Valley nature reserve at the moment... I'll add more details when I get back

**Comment by edent** [comment] 2023-03-18 20:03
I can't see that screenshot - but it looks like the website is showing the 7 benches you uploaded. Should there be more?

**Comment by edent** [comment] 2023-05-14 20:30
Any update to this Mike?

**Comment by computamike** [comment] 2023-05-14 21:10
Sorry @edent i can confirm that it looks OK now.  What I was saying at the time was extra benches... ![Screenshot_20230318_133659_DuckDuckGo.jpg](https://github.com/openbenches/openbenches.org/assets/464876/0099e9fd-b3e3-49c0-81fd-4b0c3d1e9f99)

It was showing 5 benches... I've tried attaching again

**Comment by computamike** [comment] 2023-05-14 21:10
That bench I think was in Manchester and it's not a bench I think I recorded

**Comment by edent** [comment] 2023-05-14 21:23
Ah, I see. It was probably a cache issue. Hopefully fixed now. Thanks for the brilliant benches.

**Closed by edent** 2023-05-14 21:23 UTC
